### ISSUE TITLE
[QUESTION] What's the difference between this repo and pingcap/go-tpc ?

### ISSUE THREAD

**Issue by Lloyd-Pottiger** [PingCAP-QE/tiup-bench#1]
I am not sure why maintain tiup bench as a standalone repo.  What's the difference between this repo and pingcap/go-tpc ?
When it is integrated in tiup, I will use it because I always need tiup, and then there is no need for me to download `pingcap/go-tpc`. But if tiup bench is a standalone repo, I prefer use `pingcap/go-tpc` which is more powerful.

**Comment by dbsid** [comment]
this repo is created to decouple go-tpc/go-ycsb from tiup. So users can use the latest stable and latest nightly build of go-tpc/go-ycsb through tiup. The compatibility for using `tiup bench` will not be broken.

/cc @zyguan is there anything to add？

**Comment by zyguan** [comment]
> But if tiup bench is a standalone repo, I prefer use pingcap/go-tpc which is more powerful.

The component is still published to the official tiup mirror, it's not required to be located in [pingcap/tiup](https://github.com/pingcap/tiup).

**Comment by Lloyd-Pottiger** [comment]
oh, I get it, thank you
